### ISSUE TITLE
The GNU Link Script in STM32CubeG4/Projects/NUCLEO-G491RE/Templates/STM32CubeIDE/STM32G491RETX_FLASH.ld defines wrong RAM size

### ISSUE THREAD

**Issue by Ceres-96** [STMicroelectronics/STM32CubeG4#29]
The RAM size(128KB) defined in template gnu link script exceed the real value, which should be 112 KB according to the g491 datasheet. This wrong parameter might cause hard fault during function call, since the sp register point to an illegal address.

`
/* Memories definition */
MEMORY
{
  CCMSRAM    (xrw)    : ORIGIN = 0x10000000,   LENGTH = 16K
  RAM    (xrw)    : ORIGIN = 0x20000000,   LENGTH = 128K
  ROM    (rx)    : ORIGIN = 0x08000000,   LENGTH = 512K
}
`

**Comment by RKOUSTM** [comment]
Hi @Ceres-96,

Thank you this report. An internal bug tracker has been already opened. The fix will be made available in the frame of a future release.

Thank you once more for your report.

With regards,

**Comment by RKOUSTM** [comment]
ST Internal Reference: 120645.

**Comment by ALABSTM** [comment]
Hi @Ceres-96,

The issue you reported has been finally fixed and made available in the frame of release **1.5.2**. Thank you for your patience and thank you again for having reported.

With regards,
