### ISSUE TITLE
PLLVCO_INPUT_MAX does not match with datasheet

### ISSUE THREAD

**Issue by tompiercen** [STMicroelectronics/STM32CubeG4#32]
The value [UTILS_PLLVCO_INPUT_MAX](https://github.com/STMicroelectronics/STM32CubeG4/search?q=UTILS_PLLVCO_INPUT_MAX) is defined as 8MHz in this library.

However the [datasheet](https://www.st.com/resource/en/datasheet/stm32g491ce.pdf), on page 108, suggests a value of 16MHz.

**Comment by ASELSTM** [comment]
ST Internal Reference: 126669

**Comment by RJMSTM** [comment]
Fixed in commit c356ba51f9673113cee29414857ad019c213588a
