### ISSUE TITLE
Doubled activation of TRGO in ADC example

### ISSUE THREAD

**Issue by vakochetkov** [STMicroelectronics/STM32CubeG4#35]
[There are two calls in a row of a function LL_TIM_SetTriggerOutput](https://github.com/STMicroelectronics/STM32CubeG4/blob/5b804dfaaeeafe5e87705b62099f420f822f6b28/Projects/NUCLEO-G474RE/Examples_LL/ADC/ADC_GroupsRegularInjected_Init/Src/main.c#L566). Otherwise may be I'v misunderstood the idea.

**Comment by ASELSTM** [comment]
ST Internal Reference: 130359
