### ISSUE TITLE
LED not blinking on WUT RTC_ProgrammingTheWakeUpTimer

### ISSUE THREAD

**Issue by Germ3** [STMicroelectronics/STM32CubeG4#36]
I tried the RTC_ProgrammingTheWakeUpTimer example. In the ReadMe it stated that:
- Launch the program (LED2 should toggle at each WUT (every 1 second))
But in the Main loop there is just this: 
```
    Process();
    LL_GPIO_TogglePin(LED2_GPIO_Port, LED2_Pin);
    LL_mDelay(1000);
```

So the LED2 is not blinking on WUT but just on a 1 sec Delay.

When I run this program the MCU never hits the `void RTC_WKUP_IRQHandler(void)`
Which it should do, based on the discription.

Can you please update the program so it works like it is mentiond in the Readme?

STM32CubeIDE  Version: 1.9.0 Build: 12015_20220302_0855 (UTC)
NUCLEO-G431RB

**Comment by HBOSTM** [comment]
ST Internal Reference: 139110
