### ISSUE TITLE
SPI parameter

### ISSUE THREAD

**Issue by firmware01** [STMicroelectronics/STM32CubeG4#42]
Hi,

How to set
hspi1.Init.MasterKeepIOState = SPI_MASTER_KEEP_IO_STATE_ENABLE; parameter in STM32G4 for SPI communication in Poll for conversion method.Its giving me error If I add this in MX_SPI1_Init().

**Comment by RJMSTM** [comment]
Hello @firmware01,

Could you please provide additional details, which is the error that you found?

Regards,
Rania

**Comment by RJMSTM** [comment]
Hello,
Any update please to be able to answer your question.
Thanks

**Comment by firmware01** [comment]
Yes, I can able to solve the issue.
Thanks
