### ISSUE TITLE
EXTI_ToggleLedOnIT and EXTI_ToggleLedOnIT_Init are totally the same

### ISSUE THREAD

**Issue by VictorTagayun** [STMicroelectronics/STM32CubeG4#47]
Documentation issues:

1. EXTI_ToggleLedOnIT and EXTI_ToggleLedOnIT_Init are totally the same, both main.c and ioc files
2. It mentions in the readme file that it is triggered at the falling edge but it should be rising edge as shown in its SCH. 
![image](https://github.com/STMicroelectronics/STM32CubeG4/assets/12908735/54eee9ea-7750-4c00-b83b-2faf75e989f9)
3. The ioc files labels PC4 as USER_BUTTON, while it should be PC13
![image](https://github.com/STMicroelectronics/STM32CubeG4/assets/12908735/469f827f-e52c-4180-8c16-68d51f1d5def)
4.  PC4 is not used and can be Reset_State, it is here that the external trigger is falling edge.

**Comment by TOUNSTM** [comment]
Hello @VictorTagayun,

We confirm the abnormal behavior you reported. It has been reported to our development teams for deeper analysis. We will get back to you as soon we have updates.

With regards,

**Comment by TOUNSTM** [comment]
ST Internal Reference: 169451

**Comment by TOUNSTM** [comment]
Fixed in 98f52ec7cdbbbfe1650b351bde2efb037815886d
