### ISSUE TITLE
__PKHBT and __PKHTB are STILL wrong

### ISSUE THREAD

**Issue by etheory** [STMicroelectronics/STM32CubeG4#49]
As you can see here: https://github.com/STMicroelectronics/STM32CubeG4/blob/29e23e9f45f0a495eafbfb341d98d65ca967e6ff/Drivers/CMSIS/Include/cmsis_gcc.h#L2129-L2152

The version in this repository is STILL incorrect, and should be fixed please. Here is the CMSIS version:
https://github.com/ARM-software/CMSIS_5/blob/a75f01746df18bb5b929dfb8dc6c9407fac3a0f3/CMSIS/Core/Include/cmsis_gcc.h#L2183-L2200

I reported this months ago and you closed my PR since you said it didn't match the CMSIS version, but clearly it does: https://github.com/STMicroelectronics/STM32CubeG4/pull/39

Here is the commit change where they changed this: https://github.com/ARM-software/CMSIS_5/commit/8a1fd91319106663f74ca03353a26301f5512fca

**Comment by RJMSTM** [comment]
Hello @etheory,

The latest version of CMSIS available on the STM32CubeG4 repository is 5.6.0, which does not include the most recent commits indicating that this change has already been made."

![image](https://github.com/STMicroelectronics/STM32CubeG4/assets/113367897/2009a630-66d5-48de-a5b5-df17989cabff)

I will forward this matter to the development team to determine whether we will integrate the latest version of CMSIS.

Thank you for your contribution.

Regards,

**Comment by etheory** [comment]
> Hello @etheory,
> 
> The latest version of CMSIS available on the STM32CubeG4 repository is 5.6.0, which does not include the most recent commits indicating that this change has already been made."
> 
> ![image](https://private-user-images.githubusercontent.com/113367897/318037419-2009a630-66d5-48de-a5b5-df17989cabff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MTcxMzYsIm5iZiI6MTcxMTcxNjgzNiwicGF0aCI6Ii8xMTMzNjc4OTcvMzE4MDM3NDE5LTIwMDlhNjMwLTY2ZDUtNDhkZS1hNWI1LWRmMTc5ODljYWJmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOVQxMjUzNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wY2YyYzI0NDU0YzFkMDdjODQzMzk4OGY5NTlmMWU2ZjlhOWI0Mzg5OGQ4M2IyYzY2ZjZmNzYyYzA4MWYxNTkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KEhvU5c-EntlxymWOypH9yGgt55pRBOiK8dR5TXWSIM)
> 
> I will forward this matter to the development team to determine whether we will integrate the latest version of CMSIS.
> 
> Thank you for your contribution.
> 
> Regards,

@RJMSTM CMSIS-5.6.0 is 5 years old. The commit that resolved this issue is 2 years old. That's pretty old. It definitely feels like your dependencies should be more up to date than that. Thanks.

**Comment by KRASTM** [comment]
Hello @etheory,

Thank you for the report.

Regarding your issue, indeed the version of CMSIS available on STM32G4 is v5.6.0 and it's not synchronized with ARM version, but unfortunately there is no plan to upgrade. I will keep you informed if there are any updates. Please allow me to close this issue.

Thank you in advance for your comprehension.

With regards,

**Comment by etheory** [comment]
@KRASTM v5.6.0 is now 5 years old. Why are you so out of date with your library dependencies?
By all means close the ticket, but you are costing your customers significant runtime performance by keeping the library dependencies so old.

**Comment by KRASTM** [comment]
Hi @etheory,

It is not the case, and this is not the purpose behind our support, but sometimes due to some factors we confirm the issue, but we do not have a forecast or a plan to fix it, decisions are made by our team.

Additionally, there are other series up to date with ARM and others not, for example, U5 or H5 with V5.9.0

Thank you again.
With regards,

**Comment by etheory** [comment]
Thanks @KRASTM but why all the inconsistency, why not just support the same version across all chips? It's super confusing for your users, and adds complexity that isn't necessary.

Are you open to open source contributions? It should be relatively easy to fix such a thing (I'm an applications c++ programmer by trade, I'd be happy to help improve the libraries).
