### ISSUE TITLE
conversion warnings for __NVIC_SetVector and __NVIC_GetVector

### ISSUE THREAD

**Issue by bassemaed** [STMicroelectronics/STM32CubeG4#50]
**Describe the set-up**
* MCU: STM32G474VETx
* IDE: STM32CubeIDE
* Libraries: Using the same library files provided in this repository

*Problem Description:

-  Objective: Activate the -Werror flag for the entire project.
-  Encountered Errors: Receiving errors due to conversion warnings from functions in core_cm4.h, specifically the functions __NVIC_SetVector (line 1905) and __NVIC_GetVector (line 1921).
- Error Details:

Conversion Warning:
Error Message: conversion to 'int' from 'uint32_t' {aka 'long unsigned int'} may change the sign of the result [-Werror=sign-conversion]
File: core_cm4.h
Path: /Drivers/CMSIS/Include
Line: 1908
Type: C/C++ Problem

Sign-Conversion Warning:
Error Message: conversion to 'long unsigned int' from 'long int' may change the sign of the result [-Werror=sign-conversion]
File: core_cm4.h
Path: /Drivers/CMSIS/Include
Line: 1908
Type: C/C++ Problem

Sign-Conversion Warning:
Error Message: conversion to 'long unsigned int' from 'long int' may change the sign of the result [-Werror=sign-conversion]
File: core_cm4.h
Path: /DCDC_MCU/Drivers/CMSIS/Include
Line: 1924
Type: C/C++ Problem

**Additional context**
This can be ommitted by using #pragma

**Comment by TOUNSTM** [comment]
Hello @bassemaed,

Thank you for this report. Unfortunately we don't treat aspect related to `core_cm4.h` in our GitHub repositories. These files come from Arm and we use them as is. So, these files are out of the scope of STMicroelectronics what about reporting this issue to the [ARM GitHub](https://github.com/ARM-software)?

Please allow me to close this issue now. Thank you again for your contribution.

With regards,
