### ISSUE TITLE
CMSIS DSP Library Not Updated

### ISSUE THREAD

**Issue by InductiveTiger** [STMicroelectronics/STM32CubeG4#51]
Just a basic request. Noticed the DSP library included with the firmware haven't been updated in over 4 years, and there are many new updated functions available in the newer releases.

Thank you.

**Comment by TOUNSTM** [comment]
Hello @InductiveTiger,

Unfortunately, there is no plan to update CMSIS DSP library in the short term. I will keep you informed if there are any updates.
Please allow me to close this issue.

Thank you in advance for your comprehension.

Best Regards,
